Forgot password page
sxngie/Rewwardy pull request #59
Opened 2023-11-22 04:35 UTC by sxngie

2023-11-22 04:36 UTC, sxngie commented
Should the same be implemented for the business acount?

2023-11-30 19:27 UTC, christianrosado20 requested changes

2023-11-30 19:27 UTC, christianrosado20 commented on pages/admin/forgot.js
> +   const login = async () => {
Pq tenemos esta función aquí, si el login como tal es en otra página y no se usa en esta

2023-11-30 19:27 UTC, christianrosado20 commented on pages/forgot.js
> +  const login = async () => {
lo mismo aquí

2023-11-30 19:56 UTC, sxngie commented on pages/admin/forgot.js
> +   const login = async () => {
Removed unused login function on both pages! Feel free to revise.

2023-12-01 00:20 UTC, merged